"""Init

Revision ID: 0bad0564bb11
Revises: ca2e04b5db74
Create Date: 2024-08-16 16:51:48.265419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bad0564bb11'
down_revision: Union[str, None] = 'ca2e04b5db74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_news', 'informativeness',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_news', 'informativeness',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
