"""Init

Revision ID: ba8b77b58df7
Revises: 60aeb83cd307
Create Date: 2024-08-15 15:53:39.178050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8b77b58df7'
down_revision: Union[str, None] = '60aeb83cd307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock_titles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_titles_stock_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_titles_pkey')
    )
    op.drop_table('stock_news')
    # ### end Alembic commands ###
