"""Init

Revision ID: ca2e04b5db74
Revises: 6152ad43e716
Create Date: 2024-08-16 16:32:25.678958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2e04b5db74'
down_revision: Union[str, None] = '6152ad43e716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_compound', sa.Column('fall_probability', sa.Float(), nullable=False))
    op.add_column('stock_compound', sa.Column('rise_probability', sa.Float(), nullable=False))
    op.drop_column('stock_compound', 'compound')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_compound', sa.Column('compound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('stock_compound', 'rise_probability')
    op.drop_column('stock_compound', 'fall_probability')
    # ### end Alembic commands ###
