"""Init

Revision ID: eb3d3c81e473
Revises: ba8b77b58df7
Create Date: 2024-08-16 16:00:29.807252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3d3c81e473'
down_revision: Union[str, None] = 'ba8b77b58df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_news', sa.Column('decrease', sa.Integer(), nullable=False))
    op.add_column('stock_news', sa.Column('increase', sa.Integer(), nullable=False))
    op.add_column('stock_news', sa.Column('informativeness', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_news', 'informativeness')
    op.drop_column('stock_news', 'increase')
    op.drop_column('stock_news', 'decrease')
    # ### end Alembic commands ###
