"""Init

Revision ID: f414d9249233
Revises: 0bad0564bb11
Create Date: 2024-08-18 16:47:43.469937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f414d9249233'
down_revision: Union[str, None] = '0bad0564bb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_sentiments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sentiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('positives', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('negatives', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_sentiments_stock_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_sentiments_pkey')
    )
    # ### end Alembic commands ###
